### ISSUE TITLE
Translation to Python3

### ISSUE THREAD

**Issue by rkanitz** [BoPeng/simuPOP-examples#6]
Is there any envisaged effort to comprehensively convert the examples to Python 3? It's pretty confusing at the moment to try and get started with simuPOP: The current version only works with Python 3, yet most of the examples are in Python 2.

Running the 2to3 function plus the other parsing script doesn't always work and it is troublesome and fairly frustrating.

Is this project still alive (enough) to undertake this endeavor?

**Comment by BoPeng** [comment]
I apologize but unfortunately I have many other obligations and can only focus my attention on bug fixes and major new features of simuPOP. Converting the examples to Python 3 can be time-consuming but is not very difficult. I have labeled this ticket as "help wanted" and hope that users of simuPOP can help resolve it.

Basically, someone will have to 

1. Fork the repository.
2. Run `2to3` to convert python 2 syntax to python 3, which works most of the time.
3. If applicable, convert the old `simuOpt` style parameters to `argparse` style parameters, which has to be done manually. As I wrote before, `simuOpt` was written before `argparse` and although it has some unique features such as validation and automatic creation of GUI, it does not really belong to simuPOP and has been deprecated.
4. Create and submit a PR.

**Comment by lfmcmillan** [comment]
The simOptParams2argparse.py script has the following instruction at the top: 

`# To perform conversion:`
`#`
`# python simuOptParam2argparse.py filename start_lineno ending_lineno`

But this is not accurate, because the script also requires the "name" argument, and it is not clear what that argument needs to be. For example, in examples/simuGeneticDrift.py, the script tries to print out all of the contents of simuOpt.Params and it's not clear what the corresponding "name" should be in the ...argparse.py script to convert the simuGeneticDrift script.

**Comment by lfmcmillan** [comment]
It would really help if you could provide a single example script conversion from simuOpt.Params to argparse, since it's not at all clear what conversion needs to happen in any of the example scripts. For example, the simuGeneticDrift script, what would that use of simuOpt.Params look like as argparse? 
Having one example to extrapolate from for the conversion would make it much clearer what conversion would need to happen for the other scripts. Thanks.

**Comment by BoPeng** [comment]
I have converted simuGeneticDrift.py from Python 2 to 3, which generally involves

1. Run `2to3 -w script` to convert from python 2 to 3 syntax. I have run this step on `Overdom.py` as well, which is part of the PR.
2. Manually convert `simuOpt` to `argparse` by
   * Remove `simuOpt`
   * Add `import argparse`
   * define a `parser` under `if __name__ == '__main__'`
   * add each option with `parser.add_argument`
   * Use `pars = parser.parse_args()` to parse arguments

Note that the original `simuOpt` has some options for validating user input, which is [partially supported by argparse](https://docs.python.org/3/library/argparse.html#argparse-type) but might be too troublesome to implement (e.g. define a lambda function to check the range of parameter input).

The `simuOptParam2argparse.py` script was written in Python 2, I might be able to get it work.

**Comment by BoPeng** [comment]
I have also fixed `simuOptParam2argparse.py`, which can simplify step 2 as described before. To use this script

1. Open the script in an editor (e.g. vscode), find the line range of the option list (`options=[ ....]`)
2. Call `python misc/simuOptParam2argparse.py SCRIPT.py START END`. The `--name` option is only need when the option list has a name other than `options`.
3. Remove option list from the source code, replace `pars = simuOpt.Params(options, ...` with the output from the previous script. It is helpful however to add the value of option `doc` of `simuOpt.Params` as option `decription` of `ArgumentParser`.
4. Use a code formatter (e.g. from vscode) to reformat the script.

**Comment by lfmcmillan** [comment]
Thank you very much! I'll try that new argparse conversion script

**Comment by lfmcmillan** [comment]
I tried the converter on the HWE script and it partly ran, but fell over on the "long":

```
(base) C:\Users\LFM>python Dropbox\Clustering\St_Andrews\simuoptparam2argparse.py Dropbox\Clustering\St_Andrews\simupop_examples_HWE.py 20 54
Traceback (most recent call last):
  File "C:\Users\LFM\Dropbox\Clustering\St_Andrews\simuoptparam2argparse.py", line 112, in <module>
    convert_options(args.filename, args.startline, args.endline, args.name)
  File "C:\Users\LFM\Dropbox\Clustering\St_Andrews\simuoptparam2argparse.py", line 56, in convert_options
    exec(prefix + content, value)
  File "<string>", line 33, in <module>
NameError: name 'long' is not defined
```

The corresponding line from the HWE script is
```
     'type':[int, long],
```

Thanks

**Comment by BoPeng** [comment]
Did you run 2to3 on the script first? If that script cannot take care of long, you have to manually change it to int.

**Comment by lfmcmillan** [comment]
Does the simuPOP.plotter module still exist? (some of the old example scripts still try to import it) If not, what has replaced it?

Is it correct that simuPOP now uses matplotlib instead of plotting via RPy? 

It looks like VarPlotter is no longer used in the code -- what has replaced that?

**Comment by BoPeng** [comment]
No. `simuPOP.plotter` has been removed. It was working fine but it introduced a number of nasty dependencies that made the release of simuPOP a nightmare. I could have kept it as an example/misc/utility-like module though.

Edit: yes, `plotter.py` was saved to [`deprecated`](https://github.com/BoPeng/simuPOP-examples/tree/master/deprecated)
